# Change these first
owner: kevinpapst # Your GitHub organization or username, where this repository lives
repo: cloud-status # The name of this repository

sites:
  - name: Kimai-Cloud
    url: https://www.kimai.cloud
  - name: Demo Cloud
    url: https://time.kevinpapst.de
  - name: Hacker News
    url: https://kevin.kimai.cloud

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  #cname: demo.upptime.js.org
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /cloud-status
  logoUrl: https://www.kimai.cloud/images/cloud-logo.png
  name: Kimai-Cloud Status
  introTitle: "Status page for www.kimai.cloud"
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: Kimai-Cloud
      href: https://www.kimai.cloud

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
